# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bilal El Hammouchi
title: Data Science and AI Masters Student
email: bilalelhammouchi@hotmail.com
website: bilalelhammouchi.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  BilalElHammouchi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: bilal-el-hammouchi
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Bilal and as a Master's student in Data Science and AI, a Machine Learning intern, and an accomplished freelancer, I bring a diverse blend of experience and a proven track record of solving problems on a global scale. My notable achievements include winning an AI Hackathon, serving as the secretary of Club I2A, and actively contributing to the AtlasIA open-source initiative. I am proficient in English, French, and German, and possess strong organizational and communication skills. My unique combination of technical expertise and collaborative abilities makes me a valuable asset to any team or project.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: AtlasIA
        link: atlasia.ma
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fas fa-globe
            url: atlasia.ma
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Take the first step towards creating the Moroccan ChatGPT
        description: | # this will include new lines to allow paragraphs
          I developed the backend of the atlasia.ma website using Firebase technology for the AtlasIA team. I streamlined backend processes to enable easy data import to Hugging Face, supporting open-source collaboration. Additionally, I created a responsive frontend design compatible with both mobile devices and PCs, enhancing the website's functionality and accessibility, and contributing to the overall success of the AtlasIA project.
      
      - layout: top-middle
        title: Legolingo
        description: | # this will include new lines to allow paragraphs
          I collaborated in a team of three on a project powered by OpenAI’s GPT-3.5 Turbo API, where I played a key role in integrating AI technologies to create a language-learning experience. I designed and implemented features to enhance users’ language skills, including topic-based reading, vocabulary testing, auditory comprehension exercises, and writing skill assessments. Through effective collaboration and teamwork, I actively contributed to the project's success.

      - layout: top-middle
        title: HouseAgent
        link: https://github.com/BilalElHammouchi/houseagent
        description: | # this will include new lines to allow paragraphs
          I developed a Flutter application called House Agent for the Hackathon I2A'01 contest. This app utilizes artificial neural networks and DialogFlow to provide house price predictions. It features a property input page for house details, a chat interface with a DialogFlow agent, and integrates technologies like Flutter, TensorFlow, Flask, Firebase, and PythonAnywhere. The backend, built with Flask, handles machine learning tasks and user queries, while Firebase hosts the site and PythonAnywhere hosts the backend.

      - layout: top-middle
        title: Intrusion Detection System
        link: https://github.com/BilalElHammouchi/intrusion_detection_system
        description: | # this will include new lines to allow paragraphs
          I deployed an Intrusion Detection System to enhance network security against attacks. I developed a real-time monitoring Flutter mobile app for network intrusion detection and managed Flask backend integration with a TensorFlow Lite model for efficient data processing. Additionally, I applied the CRISP methodology for structured data mining in network security.

      - layout: top-middle
        title:  Project Crowd Analysis
        link: https://github.com/BilalElHammouchi/Crowd-Analysis-GUI
        description: | # this will include new lines to allow paragraphs
          I enhanced a desktop app using YOLO and deepSORT for camera-based suspicious activity detection. I developed a user-friendly graphical interface with customtkinter for seamless user interaction and integrated a robust alarm system, enabling customizable alerts via sound, text messages, or phone calls. I played a pivotal role in the project’s evolution by bridging technical proficiency with practical solutions to enhance functionality and user experience.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Matious Digital
        link: http://www.matious.com/
        # link_text: boringcompany.com
        sub_title: Machine Learning Intern
        caption: March 2024 - Present
        description: | # this will include new lines to allow paragraphs
            During my 6-month internship as part of my master's thesis, I am developing a comprehensive web agent that harnesses the capabilities of Large Language Models (LMMs) like GPT-4 Vision. This agent aims to automate the process of using web browsers efficiently. I am utilizing technologies such as Selenium and Python to create a seamless automation workflow. This project involves experimenting with various LMMs to optimize performance and enhance the agent's capabilities, contributing to advancements in web automation and AI-driven processes.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title:  Mohammed First University
        caption: 2022 - 2024
        sub_title: MSc Data Science
        description: | # this will include new lines to allow paragraphs
          During my master's studies in Data Science and AI, I gained a deep understanding of machine learning algorithms, data analysis techniques, and advanced statistical methods. I learned to leverage big data tools and frameworks to extract meaningful insights from complex datasets. Additionally, I developed skills in natural language processing, computer vision, and neural networks, applying theoretical knowledge to practical projects and real-world problems. My studies also honed my ability to communicate technical concepts effectively and collaborate in multidisciplinary teams. I also had the honor to be one of the founding members of the first ever club in the faculty, the AI Club I2A.

      - layout: left
        title:  Mohammed First University
        caption: 2019 - 2022
        sub_title: BSc Data Science
        description: | # this will include new lines to allow paragraphs
          During my bachelor's studies in Mathematics and Computer Science, I acquired a strong foundation in mathematical principles and computational methods. I gained expertise in programming languages, data structures, algorithms, and software development techniques. This education provided me with analytical thinking skills, problem-solving abilities, and a solid understanding of mathematical modeling and optimization. I also learned to apply mathematical concepts to computer science problems, laying the groundwork for my advanced studies in Data Science and AI.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I'm not keeping up on the latest AI news and tech, some of my other interests and hobbies are:
      - Running
      - Working out
      - Musical instruments
      - Hanging out with friends
      - Gaming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
